#!/usr/bin/env bash
# Display record type and ip address of a specified domain's subdomains.
domain="$1"
prefix="$2"

lookup_subdomain () {
	sub=$1
	subdomain="${1}.${2}"
	response="$(dig "$subdomain" | grep -A1 'ANSWER SECTION' | tail -n 1)"
	echo "$response" | awk '{print "The subdomain", "'"$sub"'", "is a", $4,"record and points to", $5}'
} 

if [ "$#" -eq 2 ]
then
	lookup_subdomain "$prefix" "$domain"
else
	prefixes=("www" "lb-01" "web-01" "web-02")
	for p in "${prefixes[@]}"; do
		lookup_subdomain "$p" "$domain"
	done
fi
