#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
path_to_file=$1
server_ip=$2
username=$3
ssh_private_key=$4

if [ "$#" -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$ssh_private_key" -o "StrictHostKeyChecking no" "$path_to_file" "$username"@"$server_ip":~
fi	
