#!/usr/bin/env bash
# This script does the following:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request 
# (requesting a page) using curl, it must return a page that 
# contains the string Hello World!
apt-get update
apt-get install nginx -y

echo "Hello World!" > index.html
mv index.html /var/www/html/

service nginx restart 
