#!/usr/bin/env bash
# This script does the following:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request 
# (requesting a page) using curl, it must return a page that 
# contains the string Hello World!
sudo apt -y update
sudo apt -y install nginx
sudo echo "Hello World!" > index.html
sudo mv index.html /var/www/html
sudo service nginx restart
