#!/usr/bin/env bash
# Configure a nginx server so that /redirect_me is redirecting to another page

new_config="rewrite ^\/redirect_me$ http:\/\/gregmwangi.tech permanent;"
sed -i "/listen \[::\]:80 default_server;/a $new_config" /etc/nginx/sites-available/default
service nginx restart
