#!/usr/bin/env bash
# /redirect_me is redirecting to another page.

apt-get update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
mkdir /var/www/html/redirect_me
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.github.com/MwangiGregory permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "/listen 80 default_server/a \t error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx restart
