#!/usr/bin/env bash
# Configures my nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/custom_404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/custom_404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    add_header X-Served-By $HOSTNAME;

    location /redirect_me {
        return 301 http://gregmwangi.tech/;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart