#!/usr/bin/env bash
# Configures an nginx server to return a custom HTTP response header

hostname=$(hostname)

sed -i "/root \/etc\/nginx\/html;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default

service nginx restart
