#!/usr/bin/env bash
# Installs nginx, sets default page to be served, configures a redirect link,
# configures a custom 404 page and adds a custom header to nginx's http
# response.
apt-get update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
mkdir -p /var/www/html/redirect_me
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.github.com/MwangiGregory permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
hostname=$(hostname)
sed -i "/listen 80 default_server/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
service nginx restart
