#!/usr/bin/env bash
# Installs and configure HAproxy on your server.

# update server packages
apt-get update -y
apt-get upgrade -y

# install haproxy
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get install haproxy=2.8.\* -y

# configure haproxy
sed -i "$ a frontend hbnb_frontend\n\tbind :80\n\tdefault_backend hbnb_servers" /etc/haproxy/haproxy.cfg

sed -i "$ a backend hbnb_servers\n\tbalance roundrobin\n\tserver web-01 54.144.151.225:80\n\tserver web-02 54.173.54.146:80" /etc/haproxy/haproxy.cfg

service haproxy restart
