#!/usr/bin/env bash
#Pings an IP address it receives from the command line 5 times
ip_address="$1"
if [ "${ip_address}" ]
then
	ping -c 5 "${ip_address}"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
