#!/usr/bin/env bash
#Prints "Best School" 10 times but on the 9th iteration it prints "Hi"
i=1
while [[ $i -le 10 ]]
	do
		if [[ $i -eq 9 ]]
		then
			echo "Hi"
		else
			echo "Best School"
		fi
		(( i++ ))
done
