#!/usr/bin/env bash
#displays:
#	The content of the current directory
# 	In a list format
#	Where only the part of the name after the first dash is displayed
FILES=$(ls)
for FILE in $FILES
do
	echo "$FILE" | cut -d "-" -f2
done
