#!/usr/bin/env bash
# Configures an nginx server to run under nginx user
# and to listen on all active ips on port 8080

sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 0644 /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/
sudo -u nginx service nginx restart
