#!/usr/bin/env bash
# Configures an nginx server to run under nginx user
# and to listen on all active ips on port 8080

sed "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed "s/80/8080/g" /etc/nginx/nginx.conf
