#!/usr/bin/env bash
# Configures an nginx server to run under nginx user
# and to listen on all active ips on port 8080

sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
chown -R nginx /etc/nginx /var/log/nginx /usr/share/nginx /run/nginx.pid
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx nginx
